package hardwares;

import javax.swing.*;
import java.awt.*;

/**
 * Created by saren on 2015/11/21.
 */
public class ATMPanel {
    private JButton a7Button;
    private JButton a4Button;
    private JButton a1Button;
    private JButton a0Button;
    private JButton a8Button;
    private JButton a5Button;
    private JButton a2Button;
    private JButton dotButton;
    private JButton a9Button;
    private JButton a6Button;
    private JButton a3Button;
    private JButton a00Button;

    private JButton cancelButton;
    private JButton clearButton;
    private JButton confirmButton;
    private JButton emptyButton;

    private JButton ltButton;
    private JButton rtButton;
    private JButton lbButton;
    private JButton rbButton;

    private JLabel inputField;
    private JLabel textDisplay;

    private JPanel mainPanel;
    private JPanel keypadPanel;
    private JPanel inputPanel;
    private JPanel screenPanel;

    public JLabel getInputField() {
        return inputField;
    }

    public JLabel getTextDisplay() {
        return textDisplay;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JButton getA7Button() {
        return a7Button;
    }

    public JButton getA4Button() {
        return a4Button;
    }

    public JButton getA1Button() {
        return a1Button;
    }

    public JButton getA0Button() {
        return a0Button;
    }

    public JButton getA8Button() {
        return a8Button;
    }

    public JButton getA5Button() {
        return a5Button;
    }

    public JButton getA2Button() {
        return a2Button;
    }

    public JButton getDotButton() {
        return dotButton;
    }

    public JButton getA9Button() {
        return a9Button;
    }

    public JButton getA6Button() {
        return a6Button;
    }

    public JButton getA3Button() {
        return a3Button;
    }

    public JButton getA00Button() {
        return a00Button;
    }

    public JButton getCancelButton() {
        return cancelButton;
    }

    public JButton getClearButton() {
        return clearButton;
    }

    public JButton getConfirmButton() {
        return confirmButton;
    }

    public JButton getLtButton() {
        return ltButton;
    }

    public JButton getRtButton() {
        return rtButton;
    }

    public JButton getLbButton() {
        return lbButton;
    }

    public JButton getRbButton() {
        return rbButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setBackground(new Color(-16777216));
        mainPanel.setForeground(new Color(-16777216));
        mainPanel.setMinimumSize(new Dimension(480, 592));
        mainPanel.setOpaque(true);
        mainPanel.setPreferredSize(new Dimension(480, 592));
        screenPanel = new JPanel();
        screenPanel.setLayout(new GridBagLayout());
        screenPanel.setBackground(new Color(-16738680));
        screenPanel.setMinimumSize(new Dimension(-1, 320));
        screenPanel.setPreferredSize(new Dimension(-1, 320));
        screenPanel.setRequestFocusEnabled(true);
        mainPanel.add(screenPanel, BorderLayout.NORTH);
        lbButton = new JButton();
        lbButton.setBackground(new Color(-16738680));
        lbButton.setBorderPainted(false);
        lbButton.setEnabled(false);
        lbButton.setFont(new Font("Roboto", Font.PLAIN, 16));
        lbButton.setForeground(new Color(-1));
        lbButton.setMinimumSize(new Dimension(-1, 60));
        lbButton.setPreferredSize(new Dimension(-1, 60));
        lbButton.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        screenPanel.add(lbButton, gbc);
        rtButton = new JButton();
        rtButton.setBackground(new Color(-16738680));
        rtButton.setBorderPainted(false);
        rtButton.setEnabled(false);
        rtButton.setFont(new Font("Roboto", Font.PLAIN, 16));
        rtButton.setForeground(new Color(-1));
        rtButton.setMinimumSize(new Dimension(-1, 60));
        rtButton.setPreferredSize(new Dimension(-1, 60));
        rtButton.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        screenPanel.add(rtButton, gbc);
        textDisplay = new JLabel();
        textDisplay.setBackground(new Color(-1));
        textDisplay.setFont(new Font("Roboto", Font.PLAIN, 24));
        textDisplay.setForeground(new Color(-1));
        textDisplay.setMinimumSize(new Dimension(600, 300));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        screenPanel.add(textDisplay, gbc);
        rbButton = new JButton();
        rbButton.setBackground(new Color(-16738680));
        rbButton.setBorderPainted(false);
        rbButton.setEnabled(false);
        rbButton.setFont(new Font("Roboto", Font.PLAIN, 16));
        rbButton.setForeground(new Color(-1));
        rbButton.setMinimumSize(new Dimension(-1, 60));
        rbButton.setPreferredSize(new Dimension(-1, 60));
        rbButton.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        screenPanel.add(rbButton, gbc);
        ltButton = new JButton();
        ltButton.setBackground(new Color(-16738680));
        ltButton.setBorderPainted(false);
        ltButton.setEnabled(false);
        ltButton.setFont(new Font("Roboto", Font.PLAIN, 16));
        ltButton.setForeground(new Color(-1));
        ltButton.setMinimumSize(new Dimension(-1, 60));
        ltButton.setPreferredSize(new Dimension(-1, 60));
        ltButton.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        screenPanel.add(ltButton, gbc);
        inputPanel = new JPanel();
        inputPanel.setLayout(new GridBagLayout());
        inputPanel.setBackground(new Color(-1118482));
        inputPanel.setMinimumSize(new Dimension(0, 32));
        inputPanel.setPreferredSize(new Dimension(0, 32));
        mainPanel.add(inputPanel, BorderLayout.CENTER);
        inputField = new JLabel();
        inputField.setFont(new Font("Roboto", Font.PLAIN, 16));
        inputField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 0, 0, 8);
        inputPanel.add(inputField, gbc);
        keypadPanel = new JPanel();
        keypadPanel.setLayout(new GridBagLayout());
        keypadPanel.setBackground(new Color(-14273992));
        keypadPanel.setFocusable(true);
        keypadPanel.setForeground(new Color(-14273992));
        keypadPanel.setOpaque(true);
        mainPanel.add(keypadPanel, BorderLayout.SOUTH);
        a7Button = new JButton();
        a7Button.setBackground(new Color(-14273992));
        a7Button.setBorderPainted(false);
        a7Button.setContentAreaFilled(true);
        a7Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a7Button.setForeground(new Color(-1));
        a7Button.setMinimumSize(new Dimension(40, 60));
        a7Button.setOpaque(true);
        a7Button.setPreferredSize(new Dimension(40, 60));
        a7Button.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a7Button, gbc);
        a0Button = new JButton();
        a0Button.setBackground(new Color(-14273992));
        a0Button.setBorderPainted(false);
        a0Button.setContentAreaFilled(true);
        a0Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a0Button.setForeground(new Color(-1));
        a0Button.setMinimumSize(new Dimension(40, 60));
        a0Button.setOpaque(true);
        a0Button.setPreferredSize(new Dimension(40, 60));
        a0Button.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a0Button, gbc);
        cancelButton = new JButton();
        cancelButton.setBackground(new Color(-13154481));
        cancelButton.setBorderPainted(false);
        cancelButton.setFont(new Font("Roboto", Font.PLAIN, 24));
        cancelButton.setForeground(new Color(-1));
        cancelButton.setMinimumSize(new Dimension(100, 60));
        cancelButton.setPreferredSize(new Dimension(100, 60));
        cancelButton.setText("CANCEL");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(cancelButton, gbc);
        a4Button = new JButton();
        a4Button.setBackground(new Color(-14273992));
        a4Button.setBorderPainted(false);
        a4Button.setContentAreaFilled(true);
        a4Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a4Button.setForeground(new Color(-1));
        a4Button.setMinimumSize(new Dimension(40, 60));
        a4Button.setOpaque(true);
        a4Button.setPreferredSize(new Dimension(40, 60));
        a4Button.setText("4");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a4Button, gbc);
        a1Button = new JButton();
        a1Button.setBackground(new Color(-14273992));
        a1Button.setBorderPainted(false);
        a1Button.setContentAreaFilled(true);
        a1Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a1Button.setForeground(new Color(-1));
        a1Button.setMinimumSize(new Dimension(40, 60));
        a1Button.setOpaque(true);
        a1Button.setPreferredSize(new Dimension(40, 60));
        a1Button.setText("1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a1Button, gbc);
        a8Button = new JButton();
        a8Button.setBackground(new Color(-14273992));
        a8Button.setBorderPainted(false);
        a8Button.setContentAreaFilled(true);
        a8Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a8Button.setForeground(new Color(-1));
        a8Button.setMinimumSize(new Dimension(40, 60));
        a8Button.setOpaque(true);
        a8Button.setPreferredSize(new Dimension(40, 60));
        a8Button.setText("8");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a8Button, gbc);
        a5Button = new JButton();
        a5Button.setBackground(new Color(-14273992));
        a5Button.setBorderPainted(false);
        a5Button.setContentAreaFilled(true);
        a5Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a5Button.setForeground(new Color(-1));
        a5Button.setMinimumSize(new Dimension(40, 60));
        a5Button.setOpaque(true);
        a5Button.setPreferredSize(new Dimension(40, 60));
        a5Button.setText("5");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a5Button, gbc);
        a2Button = new JButton();
        a2Button.setBackground(new Color(-14273992));
        a2Button.setBorderPainted(false);
        a2Button.setContentAreaFilled(true);
        a2Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a2Button.setForeground(new Color(-1));
        a2Button.setMinimumSize(new Dimension(40, 60));
        a2Button.setOpaque(true);
        a2Button.setPreferredSize(new Dimension(40, 60));
        a2Button.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a2Button, gbc);
        a9Button = new JButton();
        a9Button.setBackground(new Color(-14273992));
        a9Button.setBorderPainted(false);
        a9Button.setContentAreaFilled(true);
        a9Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a9Button.setForeground(new Color(-1));
        a9Button.setMinimumSize(new Dimension(40, 60));
        a9Button.setOpaque(true);
        a9Button.setPreferredSize(new Dimension(40, 60));
        a9Button.setText("9");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a9Button, gbc);
        a6Button = new JButton();
        a6Button.setBackground(new Color(-14273992));
        a6Button.setBorderPainted(false);
        a6Button.setContentAreaFilled(true);
        a6Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a6Button.setForeground(new Color(-1));
        a6Button.setMinimumSize(new Dimension(40, 60));
        a6Button.setOpaque(true);
        a6Button.setPreferredSize(new Dimension(40, 60));
        a6Button.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a6Button, gbc);
        a3Button = new JButton();
        a3Button.setBackground(new Color(-14273992));
        a3Button.setBorderPainted(false);
        a3Button.setContentAreaFilled(true);
        a3Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a3Button.setForeground(new Color(-1));
        a3Button.setMinimumSize(new Dimension(40, 60));
        a3Button.setOpaque(true);
        a3Button.setPreferredSize(new Dimension(40, 60));
        a3Button.setText("3");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a3Button, gbc);
        dotButton = new JButton();
        dotButton.setBackground(new Color(-14273992));
        dotButton.setBorderPainted(false);
        dotButton.setContentAreaFilled(true);
        dotButton.setFont(new Font("Roboto", Font.PLAIN, 24));
        dotButton.setForeground(new Color(-1));
        dotButton.setMinimumSize(new Dimension(40, 60));
        dotButton.setOpaque(true);
        dotButton.setPreferredSize(new Dimension(40, 60));
        dotButton.setText(".");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(dotButton, gbc);
        a00Button = new JButton();
        a00Button.setBackground(new Color(-14273992));
        a00Button.setBorderPainted(false);
        a00Button.setContentAreaFilled(true);
        a00Button.setFont(new Font("Roboto", Font.PLAIN, 24));
        a00Button.setForeground(new Color(-1));
        a00Button.setMinimumSize(new Dimension(40, 60));
        a00Button.setOpaque(true);
        a00Button.setPreferredSize(new Dimension(40, 60));
        a00Button.setText("00");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(a00Button, gbc);
        clearButton = new JButton();
        clearButton.setBackground(new Color(-13154481));
        clearButton.setBorderPainted(false);
        clearButton.setFont(new Font("Roboto", Font.PLAIN, 24));
        clearButton.setForeground(new Color(-1));
        clearButton.setMinimumSize(new Dimension(100, 60));
        clearButton.setPreferredSize(new Dimension(100, 60));
        clearButton.setText("CLEAR");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(clearButton, gbc);
        confirmButton = new JButton();
        confirmButton.setBackground(new Color(-13154481));
        confirmButton.setBorderPainted(false);
        confirmButton.setFont(new Font("Roboto", Font.PLAIN, 24));
        confirmButton.setForeground(new Color(-1));
        confirmButton.setMinimumSize(new Dimension(100, 60));
        confirmButton.setPreferredSize(new Dimension(100, 60));
        confirmButton.setText("CONFIRM");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(confirmButton, gbc);
        emptyButton = new JButton();
        emptyButton.setBackground(new Color(-13154481));
        emptyButton.setBorderPainted(false);
        emptyButton.setFont(new Font("Roboto", Font.PLAIN, 24));
        emptyButton.setForeground(new Color(-1));
        emptyButton.setMinimumSize(new Dimension(100, 60));
        emptyButton.setPreferredSize(new Dimension(100, 60));
        emptyButton.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        keypadPanel.add(emptyButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
